id: video_send
name: Video Send
name[zh]: 钢珠检测推流
version: 2.4.1
author: baigenshu
desc: Path apps/stream/maix_esp32/video_send; steel ball YOLO live + phone record
desc[zh]: 路径 apps/stream/maix_esp32/video_send；钢珠检测直播；手机录制
exclude:
  - .vscode
  - dist
  - __pycache__
  - avi_mjpeg.py
files:
  - app.yaml
  - detect_util.py
  - main.py
  - web_server.py
icon: ''
