id: video_send
name: 视频推流
name[zh]: 视频推流
version: 2.2.0
author: nuedc
desc: Live stream on MaixCam-ESP; record only on phone browser
desc[zh]: 连 MaixCam-ESP 全力直播；录像仅保存在手机浏览器
exclude:
  - .vscode
  - dist
  - __pycache__
files:
  - app.yaml
  - main.py
  - web_server.py
icon: ''
