/**
 * @file ball_ctrl_cfg.h
 * @brief Single-loop visual position controller configuration.
 */
#ifndef BALL_CTRL_CFG_H
#define BALL_CTRL_CFG_H

#ifndef BALL_CTRL_DEFAULT_TARGET_MM_X100
#define BALL_CTRL_DEFAULT_TARGET_MM_X100 (0)
#endif
#ifndef BALL_CTRL_DEFAULT_FRAME_DT_MS
#define BALL_CTRL_DEFAULT_FRAME_DT_MS (40u)
#endif
#ifndef BALL_CTRL_POS_ALPHA
#define BALL_CTRL_POS_ALPHA (0.45f)
#endif
#ifndef BALL_CTRL_VEL_ALPHA
#define BALL_CTRL_VEL_ALPHA (0.20f)
#endif
#ifndef BALL_CTRL_VEL_LIMIT_MM_S
#define BALL_CTRL_VEL_LIMIT_MM_S (220.0f)
#endif
#ifndef BALL_CTRL_DYNAMIC_CENTER_LEAD_S
#define BALL_CTRL_DYNAMIC_CENTER_LEAD_S (0.04f)
#endif
#ifndef BALL_CTRL_DYNAMIC_CENTER_MAX_MM
#define BALL_CTRL_DYNAMIC_CENTER_MAX_MM (4.0f)
#endif

/* Pure visual position PID. The camera position is the only feedback. */
#ifndef BALL_CTRL_PID_KP
#define BALL_CTRL_PID_KP (0.0045f)
#endif
#ifndef BALL_CTRL_PID_KI
#define BALL_CTRL_PID_KI (0.0009f)
#endif
#ifndef BALL_CTRL_PID_KD
#define BALL_CTRL_PID_KD (0.008f)
#endif
#ifndef BALL_CTRL_PID_NEAR_ERR_MM
#define BALL_CTRL_PID_NEAR_ERR_MM (20.0f)
#endif
#ifndef BALL_CTRL_PID_NEAR_KP
#define BALL_CTRL_PID_NEAR_KP (0.0045f)
#endif
#ifndef BALL_CTRL_PID_NEAR_KI
#define BALL_CTRL_PID_NEAR_KI (0.0010f)
#endif
#ifndef BALL_CTRL_PID_INTEGRAL_MAX
#define BALL_CTRL_PID_INTEGRAL_MAX (0.16f)
#endif
#ifndef BALL_CTRL_PID_INTEGRAL_MAX_ERR_MM
#define BALL_CTRL_PID_INTEGRAL_MAX_ERR_MM (70.0f)
#endif
#ifndef BALL_CTRL_PID_INTEGRAL_MAX_VEL_MM_S
#define BALL_CTRL_PID_INTEGRAL_MAX_VEL_MM_S (8.0f)
#endif
#ifndef BALL_CTRL_PID_DEADBAND_MM
#define BALL_CTRL_PID_DEADBAND_MM (1.0f)
#endif
#ifndef BALL_CTRL_OUTPUT_MAX_MM_X100
#define BALL_CTRL_OUTPUT_MAX_MM_X100 (46)
#endif
#ifndef BALL_CTRL_COMMAND_SLEW_MM_X100
#define BALL_CTRL_COMMAND_SLEW_MM_X100 (6)
#endif
#ifndef BALL_CTRL_COMMAND_EPS_MM_X100
#define BALL_CTRL_COMMAND_EPS_MM_X100 (1)
#endif

#ifndef BALL_CTRL_SETTLED_ERR_MM
#define BALL_CTRL_SETTLED_ERR_MM (4.0f)
#endif
#ifndef BALL_CTRL_SETTLED_VEL_MM_S
#define BALL_CTRL_SETTLED_VEL_MM_S (4.0f)
#endif
#ifndef BALL_CTRL_SETTLED_CONFIRM_FRAMES
#define BALL_CTRL_SETTLED_CONFIRM_FRAMES (5u)
#endif
#ifndef BALL_CTRL_SETTLED_EXIT_ERR_MM
#define BALL_CTRL_SETTLED_EXIT_ERR_MM (10.0f)
#endif
#ifndef BALL_CTRL_SETTLED_EXIT_VEL_MM_S
#define BALL_CTRL_SETTLED_EXIT_VEL_MM_S (12.0f)
#endif

#ifndef BALL_CTRL_TARGET_MIN_MM_X100
#define BALL_CTRL_TARGET_MIN_MM_X100 (-10000)
#endif
#ifndef BALL_CTRL_TARGET_MAX_MM_X100
#define BALL_CTRL_TARGET_MAX_MM_X100 (10000)
#endif

#ifndef BALL_CTRL_HOLD_LEVEL_ON_LOSS
#define BALL_CTRL_HOLD_LEVEL_ON_LOSS (1)
#endif
#ifndef BALL_CTRL_LOST_FRAME_GRACE
#define BALL_CTRL_LOST_FRAME_GRACE (2u)
#endif
#ifndef BALL_CTRL_LOST_DISABLE_MS
#define BALL_CTRL_LOST_DISABLE_MS (500u)
#endif
#ifndef BALL_CTRL_LINK_TIMEOUT_MS
#define BALL_CTRL_LINK_TIMEOUT_MS (200u)
#endif

#ifndef BALL_CTRL_STEPPER_SPS
#define BALL_CTRL_STEPPER_SPS (1800u)
#endif
#ifndef BALL_CTRL_STEPPER_ACCEL
#define BALL_CTRL_STEPPER_ACCEL (8000u)
#endif

#ifndef BALL_CTRL_SIGN
#define BALL_CTRL_SIGN (1.0f)
#endif

#endif /* BALL_CTRL_CFG_H */