/**
 * @file ball_ctrl_cfg.h
 * @brief Visual ball-position PID configuration.
 */
#ifndef BALL_CTRL_CFG_H
#define BALL_CTRL_CFG_H

#ifndef BALL_CTRL_DEFAULT_TARGET_MM_X100
#define BALL_CTRL_DEFAULT_TARGET_MM_X100 (0)
#endif
#ifndef BALL_CTRL_DEFAULT_FRAME_DT_MS
#define BALL_CTRL_DEFAULT_FRAME_DT_MS (40u)
#endif
#ifndef BALL_CTRL_FRAME_DT_MIN_MS
#define BALL_CTRL_FRAME_DT_MIN_MS (20u)
#endif
#ifndef BALL_CTRL_FRAME_DT_MAX_MS
#define BALL_CTRL_FRAME_DT_MAX_MS (100u)
#endif

/* Constant-velocity alpha-beta observer. */
#ifndef BALL_CTRL_OBSERVER_ALPHA
#define BALL_CTRL_OBSERVER_ALPHA (0.55f)
#endif
#ifndef BALL_CTRL_OBSERVER_BETA
#define BALL_CTRL_OBSERVER_BETA (0.08f)
#endif
#ifndef BALL_CTRL_OBSERVER_INNOVATION_MAX_MM
#define BALL_CTRL_OBSERVER_INNOVATION_MAX_MM (35.0f)
#endif
#ifndef BALL_CTRL_VEL_LIMIT_MM_S
#define BALL_CTRL_VEL_LIMIT_MM_S (300.0f)
#endif

/*
 * Position PID with derivative on measurement. Far gains accelerate the ball;
 * near gains reduce proportional action and add damping before target crossing.
 * Output is the abstract boom-tilt unit consumed by Stepper_SetTargetMm_x100().
 */
#ifndef BALL_CTRL_PID_FAR_KP
#define BALL_CTRL_PID_FAR_KP (0.0035f)
#endif
#ifndef BALL_CTRL_PID_FAR_KD
#define BALL_CTRL_PID_FAR_KD (0.0090f)
#endif
#ifndef BALL_CTRL_PID_NEAR_KP
#define BALL_CTRL_PID_NEAR_KP (0.0025f)
#endif
#ifndef BALL_CTRL_PID_NEAR_KD
#define BALL_CTRL_PID_NEAR_KD (0.0140f)
#endif
#ifndef BALL_CTRL_PID_NEAR_ZONE_MM
#define BALL_CTRL_PID_NEAR_ZONE_MM (40.0f)
#endif
#ifndef BALL_CTRL_PID_KI
#define BALL_CTRL_PID_KI (0.0010f)
#endif
#ifndef BALL_CTRL_PID_INTEGRAL_OUTPUT_MAX
#define BALL_CTRL_PID_INTEGRAL_OUTPUT_MAX (0.08f)
#endif
#ifndef BALL_CTRL_PID_INTEGRAL_ZONE_MM
#define BALL_CTRL_PID_INTEGRAL_ZONE_MM (35.0f)
#endif
#ifndef BALL_CTRL_PID_INTEGRAL_VEL_MAX_MM_S
#define BALL_CTRL_PID_INTEGRAL_VEL_MAX_MM_S (25.0f)
#endif
#ifndef BALL_CTRL_PID_INTEGRAL_LEAK_PER_S
#define BALL_CTRL_PID_INTEGRAL_LEAK_PER_S (0.8f)
#endif
#ifndef BALL_CTRL_PID_CROSSING_I_RETAIN
#define BALL_CTRL_PID_CROSSING_I_RETAIN (0.20f)
#endif
#ifndef BALL_CTRL_PID_DEADBAND_MM
#define BALL_CTRL_PID_DEADBAND_MM (0.8f)
#endif
#ifndef BALL_CTRL_PID_DEADBAND_VEL_MM_S
#define BALL_CTRL_PID_DEADBAND_VEL_MM_S (4.0f)
#endif

#ifndef BALL_CTRL_OUTPUT_MAX_MM_X100
#define BALL_CTRL_OUTPUT_MAX_MM_X100 (24)
#endif
/* 固定预设轨迹可使用比普通闭环更大的、已标定的摆臂幅度。 */
#ifndef BALL_CTRL_OVERRIDE_OUTPUT_MAX_MM_X100
#define BALL_CTRL_OVERRIDE_OUTPUT_MAX_MM_X100 (48)
#endif
#ifndef BALL_CTRL_PRESET_OUTPUT_MAX_MM_X100
#define BALL_CTRL_PRESET_OUTPUT_MAX_MM_X100 (42)
#endif
#ifndef BALL_CTRL_COMMAND_RATE_UNIT_S
#define BALL_CTRL_COMMAND_RATE_UNIT_S (1.5f)
#endif
#ifndef BALL_CTRL_PRESET_COMMAND_RATE_UNIT_S
#define BALL_CTRL_PRESET_COMMAND_RATE_UNIT_S (1.4f)
#endif
#ifndef BALL_CTRL_PRESET_BRAKE_COMMAND_RATE_UNIT_S
#define BALL_CTRL_PRESET_BRAKE_COMMAND_RATE_UNIT_S (6.0f)
#endif
#ifndef BALL_CTRL_PRESET_PID_FAR_KP
#define BALL_CTRL_PRESET_PID_FAR_KP (0.0060f)
#endif
#ifndef BALL_CTRL_PRESET_PID_NEAR_KP
#define BALL_CTRL_PRESET_PID_NEAR_KP (0.0035f)
#endif
#ifndef BALL_CTRL_PRESET_PID_KI
#define BALL_CTRL_PRESET_PID_KI (0.0012f)
#endif
#ifndef BALL_CTRL_PRESET_PID_INTEGRAL_OUTPUT_MAX
#define BALL_CTRL_PRESET_PID_INTEGRAL_OUTPUT_MAX (0.12f)
#endif
#ifndef BALL_CTRL_PRESET_PID_FAR_KD
#define BALL_CTRL_PRESET_PID_FAR_KD (0.0300f)
#endif
#ifndef BALL_CTRL_PRESET_PID_NEAR_KD
#define BALL_CTRL_PRESET_PID_NEAR_KD (0.0450f)
#endif
#ifndef BALL_CTRL_PRESET_STICTION_COMPENSATION
#define BALL_CTRL_PRESET_STICTION_COMPENSATION (0.12f)
#endif
#ifndef BALL_CTRL_PRESET_STICTION_ERROR_MM
#define BALL_CTRL_PRESET_STICTION_ERROR_MM (4.0f)
#endif
#ifndef BALL_CTRL_OVERRIDE_COMMAND_RATE_UNIT_S
#define BALL_CTRL_OVERRIDE_COMMAND_RATE_UNIT_S (5.0f)
#endif
#ifndef BALL_CTRL_COMMAND_EPS_MM_X100
#define BALL_CTRL_COMMAND_EPS_MM_X100 (1)
#endif

#ifndef BALL_CTRL_SETTLED_ERR_MM
#define BALL_CTRL_SETTLED_ERR_MM (5.0f)
#endif
#ifndef BALL_CTRL_SETTLED_VEL_MM_S
#define BALL_CTRL_SETTLED_VEL_MM_S (3.0f)
#endif
#ifndef BALL_CTRL_SETTLED_CONFIRM_FRAMES
#define BALL_CTRL_SETTLED_CONFIRM_FRAMES (8u)
#endif
#ifndef BALL_CTRL_SETTLED_EXIT_ERR_MM
#define BALL_CTRL_SETTLED_EXIT_ERR_MM (8.0f)
#endif

#ifndef BALL_CTRL_TARGET_MIN_MM_X100
#define BALL_CTRL_TARGET_MIN_MM_X100 (-10000)
#endif
#ifndef BALL_CTRL_TARGET_MAX_MM_X100
#define BALL_CTRL_TARGET_MAX_MM_X100 (10000)
#endif

#ifndef BALL_CTRL_HOLD_LEVEL_ON_LOSS
#define BALL_CTRL_HOLD_LEVEL_ON_LOSS (1)
#endif
#ifndef BALL_CTRL_LOST_FRAME_GRACE
#define BALL_CTRL_LOST_FRAME_GRACE (2u)
#endif
#ifndef BALL_CTRL_LOST_DISABLE_MS
#define BALL_CTRL_LOST_DISABLE_MS (500u)
#endif
#ifndef BALL_CTRL_LINK_TIMEOUT_MS
#define BALL_CTRL_LINK_TIMEOUT_MS (200u)
#endif

#ifndef BALL_CTRL_STEPPER_SPS
#define BALL_CTRL_STEPPER_SPS (3500u)
#endif
#ifndef BALL_CTRL_STEPPER_ACCEL
#define BALL_CTRL_STEPPER_ACCEL (40000u)
#endif

#ifndef BALL_CTRL_SIGN
#define BALL_CTRL_SIGN (1.0f)
#endif

#endif /* BALL_CTRL_CFG_H */