#ifndef PRESET_MOTION_CFG_H
#define PRESET_MOTION_CFG_H

#ifndef PRESET_MOTION_POSITIVE_TARGET_MM_X100
#define PRESET_MOTION_POSITIVE_TARGET_MM_X100 (5000)
#endif
#ifndef PRESET_MOTION_NEGATIVE_TARGET_MM_X100
#define PRESET_MOTION_NEGATIVE_TARGET_MM_X100 (-5000)
#endif
#ifndef PRESET_MOTION_WAYPOINT_TOLERANCE_MM_X100
#define PRESET_MOTION_WAYPOINT_TOLERANCE_MM_X100 (1000)
#endif
#ifndef PRESET_MOTION_POSITIVE_TURN_MM_X100
#define PRESET_MOTION_POSITIVE_TURN_MM_X100 \
	(PRESET_MOTION_POSITIVE_TARGET_MM_X100 - \
		PRESET_MOTION_WAYPOINT_TOLERANCE_MM_X100)
#endif

/*
 * 长距离段使用位置+速度预测制动；负端由位置/速度窗口直接停住。
 * 摆臂命令是抽象倾角单位的 0.01 倍，正值推动小球向视觉正方向。
 */
#ifndef PRESET_MOTION_POSITIVE_PUSH_ROD_MM_X100
#define PRESET_MOTION_POSITIVE_PUSH_ROD_MM_X100 (30)
#endif
#ifndef PRESET_MOTION_POSITIVE_BRAKE_ROD_MM_X100
#define PRESET_MOTION_POSITIVE_BRAKE_ROD_MM_X100 (-34)
#endif
#ifndef PRESET_MOTION_NEGATIVE_PUSH_ROD_MM_X100
#define PRESET_MOTION_NEGATIVE_PUSH_ROD_MM_X100 (-22)
#endif
#ifndef PRESET_MOTION_NEGATIVE_BRAKE_ROD_MM_X100
#define PRESET_MOTION_NEGATIVE_BRAKE_ROD_MM_X100 (22.25f)
#endif
#ifndef PRESET_MOTION_PREDICT_BRAKE_TIME_MS
#define PRESET_MOTION_PREDICT_BRAKE_TIME_MS (300u)
#endif
#ifndef PRESET_MOTION_NEGATIVE_APPROACH_START_MM_X100
#define PRESET_MOTION_NEGATIVE_APPROACH_START_MM_X100 (500)
#endif
#ifndef PRESET_MOTION_NEGATIVE_STOP_TARGET_MM_X100
#define PRESET_MOTION_NEGATIVE_STOP_TARGET_MM_X100 \
	(PRESET_MOTION_NEGATIVE_TARGET_MM_X100)
#endif
#ifndef PRESET_MOTION_NEGATIVE_STOP_TOLERANCE_MM_X100
#define PRESET_MOTION_NEGATIVE_STOP_TOLERANCE_MM_X100 (600)
#endif
#ifndef PRESET_MOTION_NEGATIVE_STOP_SPEED_MM_S
#define PRESET_MOTION_NEGATIVE_STOP_SPEED_MM_S (3.0f)
#endif
#ifndef PRESET_MOTION_NEGATIVE_STOP_CONFIRM_FRAMES
#define PRESET_MOTION_NEGATIVE_STOP_CONFIRM_FRAMES (8u)
#endif
#ifndef PRESET_MOTION_NEGATIVE_APPROACH_MAX_SPEED_MM_S
#define PRESET_MOTION_NEGATIVE_APPROACH_MAX_SPEED_MM_S (24.0f)
#endif
#ifndef PRESET_MOTION_NEGATIVE_APPROACH_TIME_S
#define PRESET_MOTION_NEGATIVE_APPROACH_TIME_S (0.70f)
#endif
#ifndef PRESET_MOTION_NEGATIVE_SPEED_FEEDFORWARD_ROD_MM_X100
#define PRESET_MOTION_NEGATIVE_SPEED_FEEDFORWARD_ROD_MM_X100 (8.0f)
#endif
#ifndef PRESET_MOTION_NEGATIVE_SPEED_KP_ROD_PER_MM_S
#define PRESET_MOTION_NEGATIVE_SPEED_KP_ROD_PER_MM_S (2.0f)
#endif
#ifndef PRESET_MOTION_NEGATIVE_APPROACH_MAX_DRIVE_ROD_MM_X100
#define PRESET_MOTION_NEGATIVE_APPROACH_MAX_DRIVE_ROD_MM_X100 (28.0f)
#endif
#ifndef PRESET_MOTION_NEGATIVE_APPROACH_MIN_PROGRESS_SPEED_MM_S
#define PRESET_MOTION_NEGATIVE_APPROACH_MIN_PROGRESS_SPEED_MM_S (3.0f)
#endif
#ifndef PRESET_MOTION_STEPPER_SPS
#define PRESET_MOTION_STEPPER_SPS (1400u)
#endif
#ifndef PRESET_MOTION_STEPPER_ACCEL
#define PRESET_MOTION_STEPPER_ACCEL (8000u)
#endif

/* 视觉 O 点有固定偏差时，也不能让预设永远卡在置零等待阶段。 */
#ifndef PRESET_MOTION_ARMING_ZERO_MAX_MS
#define PRESET_MOTION_ARMING_ZERO_MAX_MS (100u)
#endif

#endif /* PRESET_MOTION_CFG_H */