id: steel_ball_detect
name: Steel Ball Detect
name[zh]: 钢珠检测
version: 1.0.0
author: line_tracker_car
desc: YOLOv8 steel ball detector
desc[zh]: 钢珠检测（YOLOv8）
exclude:
  - .vscode
  - dist
  - __pycache__
  - report.json
files:
  - app.yaml
  - main.py
  - steel_ball.mud
  - steel_ball_int8.cvimodel
